[#33] No longer supply stlib paths
eclipse-uprotocol/up-transport-vsomeip-rust pull request #34
Opened 2024-11-14 16:29 UTC by dmacattack

* Add build script to set the c++ paths. 
  * If there's only 1 directory, variable is set
  * if there are more than 1 directory, the user is prompted: 

![image](https://github.com/user-attachments/assets/f56c8578-c69d-4c98-b2bc-9df79b75d6eb)
 
* update README accordingly

2024-11-20 14:48 UTC, PLeVasseur commented
Hey @dmacattack -- thanks for the contribution! Is there any way to incorporate this into the CI to ensure that it's used as a part of it and validated?

2024-12-27 19:34 UTC, dmacattack commented
opening this PR. seems like obtain_and_build_vsomeip is failing just like it did on PR #35 
https://github.com/eclipse-uprotocol/up-transport-vsomeip-rust/actions/runs/11936008823/job/34217646323

I'll create an issue for this

2025-01-07 17:11 UTC, dmacattack commented
I went back in the history of this project and found the ones that succeeded were in fact ubuntu 22.04. I dont have 24 installed, but I would bet vsomeip doesnt build on it either (not just a workflow issue). 
Ubuntu changes dependent libs here and there, not uncommon. So likely, theres a dependency not quite resolved, and yes I burned a lot of githubs time to find this. Sorry about that.

2025-01-07 22:30 UTC, PLeVasseur commented
Hey @dmacattack -- thanks for troubleshooting! I'll put some time aside to review :)

2025-01-08 18:47 UTC, PLeVasseur requested changes
Hey @dmacattack -- thanks for doing the troubleshooting around Boost in this PR too!

I left a few suggestions. Could you take a look?

2025-01-08 18:47 UTC, PLeVasseur commented on up-transport-vsomeip/tests/point_to_point.rs
> +    while (Instant::now().duration_since(start_time) < duration) && (iterations < MAX_ITERATIONS) {
IIRC the issue here you found was that without bounding the iterations we're saturating the TCP/IP connection, potentially leading to packets that take "too long" to arrive, right?

I think it'd be good to make a note of why the iteration bound was added in each file as a comment so we don't forget and add this problem back in.

2025-01-08 18:47 UTC, PLeVasseur commented on vsomeip-sys/README.md
> +source ../build/env_setup.sh
I think you changed the shell script name after writing this line probably.

```suggestion
source ../build/envsetup.sh
```

2025-01-08 18:47 UTC, PLeVasseur commented on vsomeip-sys/README.md
> +VSOMEIP_INSTALL_PATH=<path/to/where/to/install/vsomeip> cargo build
This is building using the `bundled` feature, so we don't need this environment variable set in this case.

```suggestion
cargo build
```

There's a section down below that explains `VSOMEIP_INSTALL_PATH` can be optionally set to install vsomeip at that location.

2025-01-08 18:47 UTC, PLeVasseur commented on vsomeip-sys/README.md
> +VSOMEIP_INSTALL_PATH=<path/to/where/to/install/vsomeip> cargo build --no-default-features
```suggestion
VSOMEIP_INSTALL_PATH=<path/to/where/vsomeip/is/installed> cargo build --no-default-features
```

2025-01-08 18:47 UTC, PLeVasseur commented on .github/workflows/bundled-lint-and-test.yaml
> +    runs-on: ubuntu-22.04
Note that I opened #38 in which it's shown by @dmacattack on a possible work-around vsomeip has suggested.

We should address this in a follow-up PR.

2025-01-08 19:13 UTC, dmacattack commented on up-transport-vsomeip/tests/point_to_point.rs
> +    while (Instant::now().duration_since(start_time) < duration) && (iterations < MAX_ITERATIONS) {
good call I can add that comment, and yes. On my local machine I found the network buffer to be full, and the TCP retransmissions were constantly being requested. With an absurd delay for the test, it did work, but we dont need this amount of data to validate the test.

2025-01-09 12:24 UTC, PLeVasseur approved these changes
Great! LGTM

Can you squash to one commit and we'll merge?

2025-01-09 17:19 UTC, merged

2025-02-27 14:43 UTC, PLeVasseur commented on .github/workflows/bundled-lint-and-test.yaml
> +    runs-on: ubuntu-22.04
Link for @olitha